---
- name: Test that we have an ACI host, ACI username, and ACI password
  fail:
    msg: 'Please define the following variables: hostname, username and password.'
  when: hostname is not defined or username is not defined or password is not defined
  vars:
    login_info: &login_info
      host: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"

- name: ENSURE TENANT VRF EXISTS
  aci_vrf:
    <<: *login_info
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    vrf: "{{ vrf }}"
    description: "VRF Created Using Ansible"

- name: ENSURE TENANT BRIDGE DOMAIN EXISTS
  aci_bd:
    <<: *login_info
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    bd: "{{ bd }}"
    vrf: "{{ vrf }}"
    description: "BD Created Using Ansible"

- name: ENSURE BRIDGE DOMAIN SUBNET EXISTS
  aci_bd_subnet:
    <<: *login_info
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    bd: "{{ bd }}"
    gateway: "{{ gateway }}"
    mask: "{{ mask }}"
    description: "Subnet Created Using Ansible"